salesforce_creds:
       uname: "mahima.sapra@apisero.com"
       pass: "![sru9szix1IhWeDunKdSwNQ==]"
       sec_token: "![5mopPOU2mUAIY0Ez+zyR03sueAMEzuCIa+ih8MyTf8w=]"
       auth_url : "https://login.salesforce.com/services/Soap/u/49.0"
database:
  host: "localhost"
  port: "3306"
  user: "root" 
  db_pass: "![F8qCbTucK3PjTQvwp42eNA==]"
  database_name: "employee"
file:
   path: file
   file_name: data.csv
email:
  host: "smtp.gmail.com"
  port: "587"
  user: "![dqe5vmMEK/Ex4grCV/krKPQgTrYB+tGLW7QuXPlNdIg=]"
  passw: "![sru9szix1IhWeDunKdSwNQ==]"
  connection:
    starttls: "mail.smtp.starttls.enable"
    starttls_value: "true"
       